import SwiftUI

struct HomeView: View {
    @EnvironmentObject private var appState: AppState
    var body: some View {
        NavigationStack { ZStack { StormTheme.backgroundGradient.ignoresSafeArea(); ScrollView(showsIndicators: false) { VStack(spacing: 18) { HeaderView(); AlertsBanner(alerts: appState.alerts); CurrentConditionsCard(weather: appState.currentWeather); HourlyStrip(hourly: appState.hourly); DailyForecastCard(days: appState.daily); ConditionsGrid(weather: appState.currentWeather) }.padding(20) } }.navigationBarHidden(true) }
    }
}
private struct HeaderView: View { var body: some View { HStack { VStack(alignment: .leading, spacing: 4) { Text("Stormin' Shane").font(.system(size: 30, weight: .heavy, design: .rounded)); Text("Live storm desk").font(.subheadline).foregroundStyle(.secondary) }; Spacer(); RoundedRectangle(cornerRadius: 14).fill(StormTheme.cyan.opacity(0.18)).frame(width: 52, height: 52).overlay(Image(systemName: "cloud.bolt.fill").foregroundStyle(StormTheme.cyan).font(.title2)).accessibilityLabel("Stormin' Shane logo placeholder") } } }
private struct AlertsBanner: View { let alerts: [WeatherAlert]; var body: some View { if let alert = alerts.first { HStack(spacing: 12) { Image(systemName: "exclamationmark.triangle.fill").foregroundStyle(StormTheme.amber); VStack(alignment: .leading) { Text(alert.title).font(.headline); Text(alert.expires).font(.caption).foregroundStyle(.secondary) }; Spacer() }.padding().glassCard() } } }
private struct CurrentConditionsCard: View { let weather: CurrentWeather; var body: some View { VStack(alignment: .leading, spacing: 12) { HStack(alignment: .top) { VStack(alignment: .leading) { Text("\(weather.temperature)°").font(.system(size: 86, weight: .black, design: .rounded)).minimumScaleFactor(0.8); Text(weather.condition).font(.title3.weight(.semibold)); Text("Feels like \(weather.feelsLike)° • H:\(weather.high)° L:\(weather.low)°").foregroundStyle(.secondary) }; Spacer(); Image(systemName: "cloud.bolt.rain.fill").font(.system(size: 54)).symbolRenderingMode(.palette).foregroundStyle(StormTheme.amber, StormTheme.cyan, .gray) } }.padding(22).glassCard() } }
private struct HourlyStrip: View { let hourly: [HourlyForecast]; var body: some View { ScrollView(.horizontal, showsIndicators: false) { HStack(spacing: 12) { ForEach(hourly) { item in VStack(spacing: 8) { Text(item.hour).font(.caption).foregroundStyle(.secondary); Image(systemName: item.symbol).foregroundStyle(StormTheme.cyan); Text("\(item.temperature)°").font(.headline); ProgressView(value: Double(item.precipChance), total: 100).tint(StormTheme.cyan).frame(width: 52) }.padding(12).frame(width: 82).glassCard() } } } } }
private struct DailyForecastCard: View { let days: [DailyForecast]; var body: some View { VStack(spacing: 12) { ForEach(days) { day in HStack { Text(day.day).frame(width: 58, alignment: .leading); Image(systemName: day.symbol).foregroundStyle(StormTheme.cyan).frame(width: 28); Text(day.condition).foregroundStyle(.secondary); Spacer(); Text("\(day.high)° / \(day.low)°").fontWeight(.semibold) } } }.padding().glassCard() } }
private struct ConditionsGrid: View { let weather: CurrentWeather; var body: some View { LazyVGrid(columns: [GridItem(.flexible()), GridItem(.flexible())], spacing: 12) { metric("Wind", "\(weather.windMph) mph \(weather.windDirection)", "location.north.line.fill"); metric("Humidity", "\(weather.humidity)%", "humidity.fill"); metric("Dew Point", "\(weather.dewPoint)°", "thermometer.medium"); metric("Pressure", weather.pressure, "barometer"); metric("Visibility", weather.visibility, "eye.fill"); metric("UV Index", "Moderate", "sun.max.fill") } }
    private func metric(_ title: String, _ value: String, _ icon: String) -> some View { VStack(alignment: .leading, spacing: 8) { Image(systemName: icon).foregroundStyle(StormTheme.cyan); Text(title).font(.caption).foregroundStyle(.secondary); Text(value).font(.headline) }.frame(maxWidth: .infinity, alignment: .leading).padding().glassCard() }
}
