'use client';

import { useEffect, useMemo, useState } from 'react';
import { AlertTriangle, Bell, BookmarkPlus, ChevronRight, CloudLightning, Compass, Droplets, Home, Loader2, LocateFixed, Map, Moon, Radio, RefreshCw, Search, Settings, Sun, Thermometer, Tornado, Trash2, Video, Wind } from 'lucide-react';

type Tab = 'home'|'radar'|'tornado'|'shane'|'settings';
type Place = { label:string; latitude:number; longitude:number };
type Wx = any;
const defaultPlace: Place = { label:'Columbus, Ohio', latitude:39.9612, longitude:-82.9988 };
function desc(c:number){if([95,96,99].includes(c))return'Thunderstorms';if([80,81,82,61,63,65].includes(c))return'Rain';if([71,73,75,77,85,86].includes(c))return'Snow';if([45,48].includes(c))return'Fog';if(c===0)return'Clear';if([1,2].includes(c))return'Partly Cloudy';return'Cloudy'}
function ico(c:number){if([95,96,99].includes(c))return'⛈';if([80,81,82,61,63,65].includes(c))return'🌧';if([71,73,75,77,85,86].includes(c))return'❄️';if(c===0)return'☀️';if([1,2].includes(c))return'🌤';return'☁️'}
function day(s:string,i:number){return i===0?'Today':new Date(s+'T12:00:00').toLocaleDateString([], {weekday:'short'})}
function compass(deg:number){return ['N','NE','E','SE','S','SW','W','NW'][Math.round(deg/45)%8]}

export default function App(){
 const [tab,setTab]=useState<Tab>('home'); const [place,setPlace]=useState<Place>(defaultPlace); const [data,setData]=useState<Wx|null>(null); const [loading,setLoading]=useState(true); const [error,setError]=useState(''); const [q,setQ]=useState(''); const [results,setResults]=useState<Place[]>([]); const [saved,setSaved]=useState<Place[]>([]); const [install,setInstall]=useState(false);
 useEffect(()=>{ if('serviceWorker'in navigator) navigator.serviceWorker.register('/sw.js').catch(()=>{}); setInstall(/iphone|ipad/i.test(navigator.userAgent)&&!matchMedia('(display-mode: standalone)').matches); const s=localStorage.getItem('stormin.saved'); if(s) setSaved(JSON.parse(s)); locate(false);},[]);
 useEffect(()=>{localStorage.setItem('stormin.saved',JSON.stringify(saved))},[saved]);
 async function load(p:Place){setLoading(true);setError('');setPlace(p);try{const r=await fetch(`/api/weather?lat=${p.latitude}&lon=${p.longitude}&label=${encodeURIComponent(p.label)}`,{cache:'no-store'});if(!r.ok)throw new Error('Weather data failed');setData(await r.json())}catch(e:any){setError(e.message||'Weather unavailable')}finally{setLoading(false)}}
 function locate(force=true){ if(!navigator.geolocation){load(defaultPlace);return} navigator.geolocation.getCurrentPosition(pos=>load({label:'Current Location',latitude:pos.coords.latitude,longitude:pos.coords.longitude}),()=>load(force?place:defaultPlace),{enableHighAccuracy:true,timeout:9000})}
 async function search(e?:React.FormEvent){e?.preventDefault(); if(!q.trim())return; setLoading(true); try{const r=await fetch(`/api/geocode?q=${encodeURIComponent(q)}`); const j=await r.json(); setResults(j.results||[]); if(j.results?.[0]) await load(j.results[0]);}finally{setLoading(false)}}
 const wx=useMemo(()=>data?normalize(data):null,[data]);
 return <main className="app"><div className="storm-bg"/><header className="appbar"><div><p>Stormin' Shane</p><h1>{place.label}</h1></div><button onClick={()=>locate()}>{loading?<Loader2 className="spin"/>:<LocateFixed/>}</button></header>{error&&<div className="alert danger"><AlertTriangle/><div><b>{error}</b><span>Try refresh or search another city.</span></div></div>}{tab==='home'&&<HomeScreen wx={wx} loading={loading} q={q} setQ={setQ} search={search} results={results} choose={load} save={()=>wx&&setSaved(addSaved(saved,place))} install={install} refresh={()=>load(place)}/>} {tab==='radar'&&<RadarScreen place={place}/>} {tab==='tornado'&&<TornadoScreen wx={wx} place={place}/>} {tab==='shane'&&<ShaneScreen/>} {tab==='settings'&&<SettingsScreen saved={saved} choose={load} remove={(p:Place)=>setSaved(saved.filter(x=>x.label!==p.label))}/>}<nav className="tabs">{([['home',Home],['radar',Map],['tornado',Tornado],['shane',Video],['settings',Settings]] as const).map(([id,Icon])=><button key={id} onClick={()=>setTab(id)} className={tab===id?'active':''}><Icon/><span>{id}</span></button>)}</nav></main>}
function addSaved(saved:Place[],p:Place){return saved.some(x=>x.label===p.label)?saved:[p,...saved].slice(0,8)}
function normalize(d:any){const f=d.forecast,c=f.current,dy=f.daily;return{label:d.label,lat:d.lat,lon:d.lon,temp:Math.round(c.temperature_2m),feels:Math.round(c.apparent_temperature),condition:desc(c.weather_code),code:c.weather_code,wind:Math.round(c.wind_speed_10m),windDir:compass(c.wind_direction_10m||0),humidity:c.relative_humidity_2m,dew:Math.round(c.dew_point_2m),pressure:Math.round(c.surface_pressure),visibility:Math.round((c.visibility||0)/1609),uv:Math.round(c.uv_index||0),updated:new Date(d.updatedAt).toLocaleTimeString([], {hour:'numeric',minute:'2-digit'}),hourly:f.hourly.time.slice(0,24).filter((_:string,i:number)=>i%2===0).slice(0,12).map((t:string,idx:number)=>({time:idx===0?'Now':new Date(t).toLocaleTimeString([], {hour:'numeric'}),temp:Math.round(f.hourly.temperature_2m[idx*2]),pop:f.hourly.precipitation_probability[idx*2]??0,code:f.hourly.weather_code[idx*2]})),daily:dy.time.map((t:string,i:number)=>({day:day(t,i),high:Math.round(dy.temperature_2m_max[i]),low:Math.round(dy.temperature_2m_min[i]),code:dy.weather_code[i],precip:dy.precipitation_probability_max[i]??0,sunrise:dy.sunrise[i],sunset:dy.sunset[i],uv:dy.uv_index_max[i]})),alerts:d.alerts||[]}}
function HomeScreen({wx,loading,q,setQ,search,results,choose,save,install,refresh}:any){if(!wx)return <Loading/>;return <section className="screen"><form className="search" onSubmit={search}><Search/><input value={q} onChange={(e)=>setQ(e.target.value)} placeholder="Search city or ZIP"/><button>Search</button></form>{results.length>1&&<div className="results card">{results.slice(0,4).map((r:Place)=><button key={r.label} onClick={()=>choose(r)}>{r.label}<ChevronRight/></button>)}</div>}{install&&<div className="install card">Install on iPhone: Share → Add to Home Screen</div>}{wx.alerts[0]&&<div className="alert"><AlertTriangle/><div><b>{wx.alerts[0].title}</b><span>{wx.alerts[0].severity} • expires {wx.alerts[0].expires?new Date(wx.alerts[0].expires).toLocaleTimeString([], {hour:'numeric',minute:'2-digit'}):'active'}</span></div></div>}<section className="hero card"><div><span className="condition">{wx.condition}</span><div className="temp">{wx.temp}°</div><h2>Feels like {wx.feels}°</h2><p>Updated {wx.updated} • H:{wx.daily[0].high}° L:{wx.daily[0].low}°</p></div><div className="bigicon">{ico(wx.code)}</div><button className="refresh" onClick={refresh}>{loading?<Loader2 className="spin"/>:<RefreshCw/>}</button></section><div className="actions"><button onClick={save}><BookmarkPlus/> Save location</button></div><section className="hourly">{wx.hourly.map((h:any)=><div className="hour card" key={h.time}><span>{h.time}</span><strong>{ico(h.code)}</strong><b>{h.temp}°</b><i style={{height:`${Math.max(6,h.pop/2)}px`}}/><small>{h.pop}%</small></div>)}</section><section className="daily card">{wx.daily.map((d:any)=><div className="day" key={d.day}><b>{d.day}</b><span>{ico(d.code)} {desc(d.code)} • {d.precip}%</span><strong>{d.high}° / {d.low}°</strong></div>)}</section><section className="metrics"><Metric label="Wind" value={`${wx.wind} mph ${wx.windDir}`} Icon={Wind}/><Metric label="Humidity" value={`${wx.humidity}%`} Icon={Droplets}/><Metric label="Dew Point" value={`${wx.dew}°`} Icon={Thermometer}/><Metric label="Pressure" value={`${wx.pressure} mb`} Icon={Compass}/><Metric label="Visibility" value={`${wx.visibility} mi`} Icon={Sun}/><Metric label="UV Index" value={`${wx.uv}`} Icon={Moon}/></section></section>}
function Loading(){return <div className="loading"><Loader2 className="spin"/><b>Loading live weather…</b></div>}
function Metric({label,value,Icon}:any){return <div className="metric card"><Icon/><span>{label}</span><b>{value}</b></div>}
function RadarScreen({place}:any){return <section className="screen"><div className="radarPanel card"><iframe title="Live radar" src={`https://embed.windy.com/embed2.html?lat=${place.latitude}&lon=${place.longitude}&detailLat=${place.latitude}&detailLon=${place.longitude}&zoom=7&level=surface&overlay=rain&product=radar&marker=true&calendar=now&metricWind=mph&metricTemp=%C2%B0F`}/><div className="radarHud"><b>Interactive live radar</b><span>Pinch, pan, zoom. Rain/storm layer centered on {place.label}.</span></div></div><div className="layerRow"><button className="chip active">Radar</button><button className="chip">Future: velocity</button><button className="chip">Future: lightning</button></div></section>}
function TornadoScreen({wx,place}:any){const alerts=wx?.alerts||[],tor=alerts.filter((a:any)=>/tornado/i.test(a.title));return <section className="screen"><div className="tornadoHero card"><Tornado/><h2>Tornado Tracker</h2><p>{tor.length?`${tor.length} tornado alert active near ${place.label}`:`No tornado warning detected near ${place.label}`}</p></div><div className="watchList card"><b>Active NWS Alerts</b>{alerts.length?alerts.map((a:any)=><details key={a.title} className="watch"><summary><AlertTriangle/> <span>{a.title}</span> <small>{a.severity}</small></summary><p>{a.headline||a.description}</p></details>):<p>No active NWS alerts for this point.</p>}</div></section>}
function ShaneScreen(){return <section className="screen"><div className="creator card"><div className="record"><Radio/></div><h2>Shane's Updates</h2><p>Next build: real video feed, upload dashboard, published storm updates, and push notifications.</p><button>Coming soon</button></div></section>}
function SettingsScreen({saved,choose,remove}:any){return <section className="screen"><div className="settings card"><h2>Saved Locations</h2>{saved.length?saved.map((p:Place)=><div className="saved" key={p.label}><button onClick={()=>choose(p)}>{p.label}</button><button onClick={()=>remove(p)}><Trash2/></button></div>):<p>No saved locations yet.</p>}</div><div className="settings card"><h2>Alert Preferences</h2><label><input type="checkbox" defaultChecked/> Tornado warnings</label><label><input type="checkbox" defaultChecked/> Severe thunderstorm alerts</label><label><input type="checkbox" defaultChecked/> Shane video updates</label></div></section>}
