'use client';

import dynamic from 'next/dynamic';
import { useCallback, useEffect, useMemo, useState } from 'react';
import { AlertTriangle, BookmarkPlus, CalendarDays, ChevronRight, Home, Info, Loader2, LocateFixed, Map, PlayCircle, Radio, RefreshCw, Search, Settings, ShieldAlert, Star, Trash2, Video, Wind } from 'lucide-react';

const RadarMap = dynamic(() => import('./components/RadarMap'), { ssr: false });

type Tab = 'home'|'forecast'|'radar'|'alerts'|'shane'|'settings';
type Units = 'fahrenheit'|'celsius';
type Place = { label:string; latitude:number; longitude:number };
type Prefs = { tornado:boolean; severe:boolean; shane:boolean; units:Units };
type LoadState = 'booting'|'refreshing'|'ready'|'error';
const defaultPlace: Place = { label:'Columbus, Ohio', latitude:39.9612, longitude:-82.9988 };
const defaultPrefs: Prefs = { tornado:true, severe:true, shane:true, units:'fahrenheit' };
const LS_PLACE='stormin.currentPlace.v3', LS_SAVED='stormin.saved.v3', LS_PREFS='stormin.prefs.v3';

function desc(c:number){if([95,96,99].includes(c))return'Thunderstorms';if([80,81,82,61,63,65,66,67].includes(c))return'Rain';if([71,73,75,77,85,86].includes(c))return'Snow';if([45,48].includes(c))return'Fog';if(c===0)return'Clear';if([1,2].includes(c))return'Partly Cloudy';return'Cloudy'}
function ico(c:number){if([95,96,99].includes(c))return'⛈';if([80,81,82,61,63,65,66,67].includes(c))return'🌧';if([71,73,75,77,85,86].includes(c))return'❄️';if(c===0)return'☀️';if([1,2].includes(c))return'🌤';return'☁️'}
function day(s:string,i:number){return i===0?'Today':new Date(s+'T12:00:00').toLocaleDateString([], {weekday:'short'})}
function compass(deg:number){return ['N','NE','E','SE','S','SW','W','NW'][Math.round(deg/45)%8]}
function readJson<T>(key:string,fallback:T):T{try{return JSON.parse(localStorage.getItem(key)||'')||fallback}catch{return fallback}}
function tempUnit(units:Units){return units==='celsius'?'°C':'°'}

export default function App(){
 const [tab,setTab]=useState<Tab>('home');
 const [place,setPlace]=useState<Place>(defaultPlace);
 const [raw,setRaw]=useState<any|null>(null);
 const [state,setState]=useState<LoadState>('booting');
 const [error,setError]=useState('');
 const [q,setQ]=useState('');
 const [results,setResults]=useState<Place[]>([]);
 const [saved,setSaved]=useState<Place[]>([]);
 const [prefs,setPrefsState]=useState<Prefs>(defaultPrefs);
 const [selectedDay,setSelectedDay]=useState<any|null>(null);
 const [selectedAlert,setSelectedAlert]=useState<any|null>(null);
 const [install,setInstall]=useState(false);
 const loading=state==='booting'||state==='refreshing';
 const load=useCallback(async(p:Place, units:Units=prefs.units)=>{setState(raw?'refreshing':'booting');setError('');setPlace(p);localStorage.setItem(LS_PLACE,JSON.stringify(p));try{const r=await fetch(`/api/weather?lat=${p.latitude}&lon=${p.longitude}&label=${encodeURIComponent(p.label)}&unit=${units}`,{cache:'no-store'});if(!r.ok)throw new Error('Live weather data failed');setRaw(await r.json());setState('ready')}catch(e:any){setError(e.message||'Weather unavailable');setState('error')}},[prefs.units,raw]);
 const setPrefs=(next:Prefs)=>{setPrefsState(next);localStorage.setItem(LS_PREFS,JSON.stringify(next)); if(next.units!==prefs.units) load(place,next.units)};
 useEffect(()=>{ if('serviceWorker'in navigator) navigator.serviceWorker.register('/sw.js').catch(()=>{}); setInstall(/iphone|ipad/i.test(navigator.userAgent)&&!matchMedia('(display-mode: standalone)').matches); const p=readJson(LS_PLACE, defaultPlace); const pref=readJson(LS_PREFS, defaultPrefs); setPrefsState(pref); setPlace(p); setSaved(readJson(LS_SAVED, [])); load(p,pref.units); // eslint-disable-next-line react-hooks/exhaustive-deps
 },[]);
 useEffect(()=>{localStorage.setItem(LS_SAVED,JSON.stringify(saved))},[saved]);
 function locate(){ if(!navigator.geolocation){load(defaultPlace);return} navigator.geolocation.getCurrentPosition(pos=>load({label:'Current Location',latitude:pos.coords.latitude,longitude:pos.coords.longitude}),()=>setError('Location permission denied. Search a city instead.'),{enableHighAccuracy:true,timeout:9000})}
 async function search(e?:React.FormEvent){e?.preventDefault(); if(!q.trim())return; setState('refreshing'); setError(''); try{const r=await fetch(`/api/geocode?q=${encodeURIComponent(q)}`); const j=await r.json(); const rows=j.results||[]; setResults(rows); if(rows[0]) await load(rows[0]); else {setError('No matching city found.');setState(raw?'ready':'error')}}catch{setError('Search unavailable');setState(raw?'ready':'error')}}
 const wx=useMemo(()=>raw?normalize(raw,prefs.units):null,[raw,prefs.units]);
 const save=()=>{if(!saved.some(s=>s.label===place.label))setSaved([place,...saved].slice(0,12))};
 const remove=(p:Place)=>setSaved(saved.filter(s=>s.label!==p.label));
 const visibleAlerts=wx?.alerts.filter((a:any)=> (prefs.tornado||!/tornado/i.test(a.title)) && (prefs.severe||!/severe thunderstorm/i.test(a.title))) || [];
 return <main className="app"><div className="storm-bg"/><header className="appbar"><div><p>Stormin' Shane live weather</p><h1>{place.label}</h1></div><button onClick={locate} aria-label="Use current location">{loading?<Loader2 className="spin"/>:<LocateFixed/>}</button></header>{error&&<Banner danger title={error} text="Try search, refresh, or location again."/>}{install&&<div className="install card">Install on iPhone: Share → Add to Home Screen</div>}{tab==='home'&&<HomeScreen wx={wx} loading={loading} q={q} setQ={setQ} search={search} results={results} choose={load} save={save} refresh={()=>load(place)} saved={saved}/>} {tab==='forecast'&&<ForecastScreen wx={wx} openDay={setSelectedDay}/>} {tab==='radar'&&<RadarScreen place={place}/>} {tab==='alerts'&&<AlertsScreen alerts={visibleAlerts} openAlert={setSelectedAlert}/>} {tab==='shane'&&<ShaneScreen prefs={prefs} setPrefs={setPrefs}/>} {tab==='settings'&&<SettingsScreen saved={saved} choose={load} remove={remove} prefs={prefs} setPrefs={setPrefs}/>}<nav className="tabs">{([['home',Home],['forecast',CalendarDays],['radar',Map],['alerts',ShieldAlert],['shane',Video],['settings',Settings]] as const).map(([id,Icon])=><button key={id} onClick={()=>setTab(id)} className={tab===id?'active':''}><Icon/><span>{id}</span></button>)}</nav>{selectedDay&&<DaySheet day={selectedDay} close={()=>setSelectedDay(null)}/>} {selectedAlert&&<AlertSheet alert={selectedAlert} close={()=>setSelectedAlert(null)}/>}</main>}
function normalize(d:any,units:Units){const f=d.forecast,c=f.current,dy=f.daily,u=tempUnit(units);const start=Math.max(0,f.hourly.time.findIndex((t:string)=>t>=c.time));const hourly=f.hourly.time.slice(start,start+48).map((t:string,off:number)=>{const i=start+off;return{iso:t,date:t.slice(0,10),time:off===0?'Now':new Date(t).toLocaleTimeString([], {hour:'numeric'}),temp:Math.round(f.hourly.temperature_2m[i]),feels:Math.round(f.hourly.apparent_temperature?.[i]??f.hourly.temperature_2m[i]),humidity:f.hourly.relative_humidity_2m?.[i]??null,pop:f.hourly.precipitation_probability[i]??0,rain:f.hourly.precipitation?.[i]??0,code:f.hourly.weather_code[i],wind:Math.round(f.hourly.wind_speed_10m[i]??0),gust:Math.round(f.hourly.wind_gusts_10m?.[i]??0)}});return{unit:u,label:d.label,lat:d.lat,lon:d.lon,temp:Math.round(c.temperature_2m),feels:Math.round(c.apparent_temperature),condition:desc(c.weather_code),code:c.weather_code,wind:Math.round(c.wind_speed_10m),windDir:compass(c.wind_direction_10m||0),humidity:c.relative_humidity_2m,dew:Math.round(c.dew_point_2m),pressure:Math.round(c.surface_pressure),visibility:Math.round((c.visibility||0)/1609),uv:Math.round(c.uv_index||0),aqi:d.airQuality?.current?.us_aqi??null,pm25:d.airQuality?.current?.pm2_5??null,updated:new Date(d.updatedAt).toLocaleTimeString([], {hour:'numeric',minute:'2-digit'}),hourly,daily:dy.time.map((t:string,i:number)=>({date:t,day:day(t,i),high:Math.round(dy.temperature_2m_max[i]),low:Math.round(dy.temperature_2m_min[i]),code:dy.weather_code[i],precip:dy.precipitation_probability_max[i]??0,rain:dy.precipitation_sum?.[i]??0,sunrise:dy.sunrise[i],sunset:dy.sunset[i],uv:Math.round(dy.uv_index_max[i]??0),unit:u,hours:hourly.filter((h:any)=>h.date===t)})),alerts:d.alerts||[]}}
function Banner({title,text,danger=false}:any){return <div className={`alert ${danger?'danger':''}`}><AlertTriangle/><div><b>{title}</b><span>{text}</span></div></div>}
function Loading(){return <div className="loading"><Loader2 className="spin"/><b>Loading live weather…</b><span>Getting current conditions, radar, AQI, and NWS alerts.</span></div>}
function HomeScreen({wx,loading,q,setQ,search,results,choose,save,refresh,saved}:any){if(!wx)return <Loading/>;return <section className="screen"><form className="search" onSubmit={search}><Search/><input value={q} onChange={(e)=>setQ(e.target.value)} placeholder="Search city or ZIP"/><button>Search</button></form>{results.length>1&&<div className="results card">{results.slice(0,5).map((r:Place)=><button key={r.label} onClick={()=>choose(r)}>{r.label}<ChevronRight/></button>)}</div>}{wx.alerts[0]&&<Banner title={wx.alerts[0].title} text={`${wx.alerts[0].severity} • active alert nearby`}/>}<section className="hero card"><div><span className="condition">{wx.condition}</span><div className="temp">{wx.temp}{wx.unit}</div><h2>Feels like {wx.feels}{wx.unit}</h2><p>Updated {wx.updated} • H:{wx.daily[0].high}{wx.unit} L:{wx.daily[0].low}{wx.unit}</p></div><div className="bigicon">{ico(wx.code)}</div><button className="refresh" onClick={refresh}>{loading?<Loader2 className="spin"/>:<RefreshCw/>}</button></section><div className="actions"><button onClick={save}><BookmarkPlus/> Save location</button>{saved.length>0&&<button onClick={()=>choose(saved[0])}><Star/> {saved[0].label}</button>}</div><section className="nowGrid"><Metric label="Wind" value={`${wx.wind} mph ${wx.windDir}`} Icon={Wind}/><Metric label="Humidity" value={`${wx.humidity}%`} Icon={Info}/><Metric label="AQI" value={wx.aqi==null?'—':String(wx.aqi)} Icon={Info}/></section><section className="hourly">{wx.hourly.slice(0,18).map((h:any)=><div className="hour card" key={h.iso}><span>{h.time}</span><strong>{ico(h.code)}</strong><b>{h.temp}{wx.unit}</b><i style={{height:`${Math.max(6,h.pop/2)}px`}}/><small>{h.pop}%</small></div>)}</section><section className="rainNext card"><b>Next 24 hours precipitation</b><div>{wx.hourly.slice(0,24).map((h:any)=><span key={h.iso} style={{height:`${Math.max(8,h.pop)}%`}} title={`${h.time}: ${h.pop}% rain`}/>)}</div><small>{wx.hourly[0].rain} in now • peak chance {Math.max(...wx.hourly.slice(0,24).map((h:any)=>h.pop))}%</small></section></section>}
function Metric({label,value,Icon}:any){return <div className="metric card"><Icon/><span>{label}</span><b>{value}</b></div>}
function ForecastScreen({wx,openDay}:any){if(!wx)return <Loading/>;return <section className="screen"><h2 className="screenTitle">Forecast</h2><section className="daily card">{wx.daily.map((d:any)=><button className="day rowButton" key={d.date} onClick={()=>openDay(d)}><b>{d.day}</b><span>{ico(d.code)} {desc(d.code)} • {d.precip}% • {d.rain} in</span><strong>{d.high}{wx.unit} / {d.low}{wx.unit}</strong><ChevronRight/></button>)}</section><h2 className="screenTitle smallTitle">Next 48 hours</h2><section className="detailHours card">{wx.hourly.map((h:any)=><div key={h.iso}><b>{h.time}</b><span>{ico(h.code)} {desc(h.code)}</span><strong>{h.temp}{wx.unit}</strong><small>Feels {h.feels}{wx.unit} • Wind {h.wind} mph • Gust {h.gust} mph • Humidity {h.humidity}%</small></div>)}</section></section>}
function RadarScreen({place}:any){return <section className="screen"><div className="radarPanel card"><RadarMap lat={place.latitude} lon={place.longitude} label={place.label}/><div className="radarHud"><b>RainViewer radar</b><span>Pan, zoom, scrub frames, or press play. Centered on {place.label}.</span></div></div><div className="layerRow"><button className="chip active">Reflectivity</button><button className="chip">Street map</button><button className="chip">Timeline scrubber</button></div></section>}
function AlertsScreen({alerts,openAlert}:any){return <section className="screen"><h2 className="screenTitle">Severe weather alerts</h2>{alerts.length?alerts.map((a:any)=><button className="alertItem card" key={a.title+a.expires} onClick={()=>openAlert(a)}><AlertTriangle/><div><b>{a.title}</b><span>{a.severity} • {a.urgency} • expires {a.expires?new Date(a.expires).toLocaleTimeString([], {hour:'numeric',minute:'2-digit'}):'unknown'}</span></div><ChevronRight/></button>):<div className="empty card"><ShieldAlert/><b>No active NWS alerts here.</b><span>Stormin' Shane will keep watching.</span></div>}</section>}
function ShaneScreen({prefs,setPrefs}:any){return <section className="screen"><div className="creator card"><div className="record"><Radio/></div><h2>Shane's Updates</h2><p>Ready for a real creator feed: live stream, severe-weather posts, and sponsor cards can plug in here without rebuilding the app shell.</p><button><PlayCircle/> Watch latest update</button></div><div className="settings card"><h2>Subscribe</h2><label><input type="checkbox" checked={prefs.shane} onChange={(e)=>setPrefs({...prefs,shane:e.target.checked})}/> Push Shane's weather updates</label></div></section>}
function SettingsScreen({saved,choose,remove,prefs,setPrefs}:any){return <section className="screen"><div className="settings card"><h2>Units</h2><div className="segmented"><button className={prefs.units==='fahrenheit'?'active':''} onClick={()=>setPrefs({...prefs,units:'fahrenheit'})}>Fahrenheit</button><button className={prefs.units==='celsius'?'active':''} onClick={()=>setPrefs({...prefs,units:'celsius'})}>Celsius</button></div></div><div className="settings card"><h2>Saved Locations</h2>{saved.length?saved.map((p:Place)=><div className="saved" key={p.label}><button onClick={()=>choose(p)}>{p.label}</button><button onClick={()=>remove(p)}><Trash2/></button></div>):<p>No saved locations yet. Search a city and tap Save.</p>}</div><div className="settings card"><h2>Alert Preferences</h2><label><input type="checkbox" checked={prefs.tornado} onChange={(e)=>setPrefs({...prefs,tornado:e.target.checked})}/> Show tornado warnings</label><label><input type="checkbox" checked={prefs.severe} onChange={(e)=>setPrefs({...prefs,severe:e.target.checked})}/> Show severe thunderstorm alerts</label><label><input type="checkbox" checked={prefs.shane} onChange={(e)=>setPrefs({...prefs,shane:e.target.checked})}/> Shane video updates</label></div></section>}
function DaySheet({day,close}:any){return <div className="sheet"><button className="scrim" onClick={close}/><div className="sheetCard card"><button className="close" onClick={close}>×</button><h2>{day.day}</h2><div className="sheetIcon">{ico(day.code)}</div><p>{desc(day.code)} with {day.precip}% precipitation chance and {day.rain} in expected.</p><div className="sheetGrid"><Metric label="High" value={`${day.high}${day.unit||'°'}`} Icon={Info}/><Metric label="Low" value={`${day.low}${day.unit||'°'}`} Icon={Info}/><Metric label="UV" value={day.uv} Icon={Info}/></div><h3>Daylight</h3><p>Sunrise {new Date(day.sunrise).toLocaleTimeString([], {hour:'numeric',minute:'2-digit'})} • Sunset {new Date(day.sunset).toLocaleTimeString([], {hour:'numeric',minute:'2-digit'})}</p></div></div>}
function AlertSheet({alert,close}:any){return <div className="sheet"><button className="scrim" onClick={close}/><div className="sheetCard card"><button className="close" onClick={close}>×</button><h2>{alert.title}</h2><p><b>{alert.severity}</b> • {alert.urgency} • {alert.certainty}</p><p>{alert.headline||alert.description||'No further details from NWS.'}</p></div></div>}
